<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/17 13:17:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=guardi18nex',
  'username' => 'redatkor',
  'password' => 'tajnehaslo',
  'name' => 'doctrine',
)),);
