<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/17 13:32:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=guardi18nex',
  'username' => 'redaktor',
  'password' => NULL,
  'name' => 'doctrine',
)),);
